java_binary(
    name = "other",
    srcs = glob(["src/**/*.java"]),
    main_class = "Other",
    visibility = ["//visibility:public"],
    deps = [
        "@maven//:com_fasterxml_jackson_core_jackson_databind"
    ],
)

